// Code generated by MockGen. DO NOT EDIT.
// Source: /usr/lib/go-1.9/src/hash/hash.go

// Package mock_utils is a generated GoMock package.
package mock_utils

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHash is a mock of Hash interface
type MockHash struct {
	ctrl     *gomock.Controller
	recorder *MockHashMockRecorder
}

// MockHashMockRecorder is the mock recorder for MockHash
type MockHashMockRecorder struct {
	mock *MockHash
}

// NewMockHash creates a new mock instance
func NewMockHash(ctrl *gomock.Controller) *MockHash {
	mock := &MockHash{ctrl: ctrl}
	mock.recorder = &MockHashMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHash) EXPECT() *MockHashMockRecorder {
	return m.recorder
}

// Write mocks base method
func (m *MockHash) Write(p []byte) (int, error) {
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write
func (mr *MockHashMockRecorder) Write(p interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockHash)(nil).Write), p)
}

// Sum mocks base method
func (m *MockHash) Sum(b []byte) []byte {
	ret := m.ctrl.Call(m, "Sum", b)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Sum indicates an expected call of Sum
func (mr *MockHashMockRecorder) Sum(b interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sum", reflect.TypeOf((*MockHash)(nil).Sum), b)
}

// Reset mocks base method
func (m *MockHash) Reset() {
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset
func (mr *MockHashMockRecorder) Reset() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockHash)(nil).Reset))
}

// Size mocks base method
func (m *MockHash) Size() int {
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size
func (mr *MockHashMockRecorder) Size() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockHash)(nil).Size))
}

// BlockSize mocks base method
func (m *MockHash) BlockSize() int {
	ret := m.ctrl.Call(m, "BlockSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// BlockSize indicates an expected call of BlockSize
func (mr *MockHashMockRecorder) BlockSize() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockSize", reflect.TypeOf((*MockHash)(nil).BlockSize))
}

// MockHash32 is a mock of Hash32 interface
type MockHash32 struct {
	ctrl     *gomock.Controller
	recorder *MockHash32MockRecorder
}

// MockHash32MockRecorder is the mock recorder for MockHash32
type MockHash32MockRecorder struct {
	mock *MockHash32
}

// NewMockHash32 creates a new mock instance
func NewMockHash32(ctrl *gomock.Controller) *MockHash32 {
	mock := &MockHash32{ctrl: ctrl}
	mock.recorder = &MockHash32MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHash32) EXPECT() *MockHash32MockRecorder {
	return m.recorder
}

// Write mocks base method
func (m *MockHash32) Write(p []byte) (int, error) {
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write
func (mr *MockHash32MockRecorder) Write(p interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockHash32)(nil).Write), p)
}

// Sum mocks base method
func (m *MockHash32) Sum(b []byte) []byte {
	ret := m.ctrl.Call(m, "Sum", b)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Sum indicates an expected call of Sum
func (mr *MockHash32MockRecorder) Sum(b interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sum", reflect.TypeOf((*MockHash32)(nil).Sum), b)
}

// Reset mocks base method
func (m *MockHash32) Reset() {
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset
func (mr *MockHash32MockRecorder) Reset() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockHash32)(nil).Reset))
}

// Size mocks base method
func (m *MockHash32) Size() int {
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size
func (mr *MockHash32MockRecorder) Size() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockHash32)(nil).Size))
}

// BlockSize mocks base method
func (m *MockHash32) BlockSize() int {
	ret := m.ctrl.Call(m, "BlockSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// BlockSize indicates an expected call of BlockSize
func (mr *MockHash32MockRecorder) BlockSize() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockSize", reflect.TypeOf((*MockHash32)(nil).BlockSize))
}

// Sum32 mocks base method
func (m *MockHash32) Sum32() uint32 {
	ret := m.ctrl.Call(m, "Sum32")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// Sum32 indicates an expected call of Sum32
func (mr *MockHash32MockRecorder) Sum32() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sum32", reflect.TypeOf((*MockHash32)(nil).Sum32))
}

// MockHash64 is a mock of Hash64 interface
type MockHash64 struct {
	ctrl     *gomock.Controller
	recorder *MockHash64MockRecorder
}

// MockHash64MockRecorder is the mock recorder for MockHash64
type MockHash64MockRecorder struct {
	mock *MockHash64
}

// NewMockHash64 creates a new mock instance
func NewMockHash64(ctrl *gomock.Controller) *MockHash64 {
	mock := &MockHash64{ctrl: ctrl}
	mock.recorder = &MockHash64MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHash64) EXPECT() *MockHash64MockRecorder {
	return m.recorder
}

// Write mocks base method
func (m *MockHash64) Write(p []byte) (int, error) {
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write
func (mr *MockHash64MockRecorder) Write(p interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockHash64)(nil).Write), p)
}

// Sum mocks base method
func (m *MockHash64) Sum(b []byte) []byte {
	ret := m.ctrl.Call(m, "Sum", b)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Sum indicates an expected call of Sum
func (mr *MockHash64MockRecorder) Sum(b interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sum", reflect.TypeOf((*MockHash64)(nil).Sum), b)
}

// Reset mocks base method
func (m *MockHash64) Reset() {
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset
func (mr *MockHash64MockRecorder) Reset() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockHash64)(nil).Reset))
}

// Size mocks base method
func (m *MockHash64) Size() int {
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size
func (mr *MockHash64MockRecorder) Size() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockHash64)(nil).Size))
}

// BlockSize mocks base method
func (m *MockHash64) BlockSize() int {
	ret := m.ctrl.Call(m, "BlockSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// BlockSize indicates an expected call of BlockSize
func (mr *MockHash64MockRecorder) BlockSize() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockSize", reflect.TypeOf((*MockHash64)(nil).BlockSize))
}

// Sum64 mocks base method
func (m *MockHash64) Sum64() uint64 {
	ret := m.ctrl.Call(m, "Sum64")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Sum64 indicates an expected call of Sum64
func (mr *MockHash64MockRecorder) Sum64() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sum64", reflect.TypeOf((*MockHash64)(nil).Sum64))
}
