// Code generated by MockGen. DO NOT EDIT.
// Source: i_x12_hash_wrap.go

// Package utils_mock is a generated GoMock package.
package utils_mock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockiX12HashWrap is a mock of iX12HashWrap interface
type MockiX12HashWrap struct {
	ctrl     *gomock.Controller
	recorder *MockiX12HashWrapMockRecorder
}

// MockiX12HashWrapMockRecorder is the mock recorder for MockiX12HashWrap
type MockiX12HashWrapMockRecorder struct {
	mock *MockiX12HashWrap
}

// NewMockiX12HashWrap creates a new mock instance
func NewMockiX12HashWrap(ctrl *gomock.Controller) *MockiX12HashWrap {
	mock := &MockiX12HashWrap{ctrl: ctrl}
	mock.recorder = &MockiX12HashWrapMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockiX12HashWrap) EXPECT() *MockiX12HashWrapMockRecorder {
	return m.recorder
}

// X11 mocks base method
func (m *MockiX12HashWrap) X11(arg0 []byte) []byte {
	ret := m.ctrl.Call(m, "X11", arg0)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// X11 indicates an expected call of X11
func (mr *MockiX12HashWrapMockRecorder) X11(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "X11", reflect.TypeOf((*MockiX12HashWrap)(nil).X11), arg0)
}

// Scrypt mocks base method
func (m *MockiX12HashWrap) Scrypt(data, salt []byte, N, r, p, keyLen int) ([]byte, error) {
	ret := m.ctrl.Call(m, "Scrypt", data, salt, N, r, p, keyLen)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scrypt indicates an expected call of Scrypt
func (mr *MockiX12HashWrapMockRecorder) Scrypt(data, salt, N, r, p, keyLen interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scrypt", reflect.TypeOf((*MockiX12HashWrap)(nil).Scrypt), data, salt, N, r, p, keyLen)
}
